version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: standard-version
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: write-good
    versions:
    - 1.0.4
    - 1.0.5
